# Generated by Django 6.0.4 on 2026-04-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_remove_group_members_group_status_group_students"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="group",
            unique_together={("name", "branch")},
        ),
    ]
