# Generated by Django 6.0.4 on 2026-04-27 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_branch_users_alter_branch_address_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsubscription',
            old_name='subscription',
            new_name='plan',
        ),
        migrations.RemoveField(
            model_name='studentsubscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='studentsubscription',
            name='lessons_per_month',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='pricing_grid',
            field=models.JSONField(default=1, help_text='Формат: {"8": 200, "12": 180} (кількість уроків -> ціна за урок)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='subjects',
            field=models.ManyToManyField(related_name='subscription_plans', to='branches.subject'),
        ),
        migrations.AlterField(
            model_name='studentsubscription',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.subject'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group')], max_length=20),
        ),
    ]
