# Generated by Django 6.0.4 on 2026-04-28 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_rename_subscription_studentsubscription_plan_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentsubscription",
            unique_together={("student", "subject")},
        ),
    ]
